"""Basic Structure

Revision ID: 312c1d408043
Revises: 41984a51dbb2
Create Date: 2014-12-10 22:21:47.178397

"""

# revision identifiers, used by Alembic.
revision = '312c1d408043'
down_revision = '41984a51dbb2'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('continent',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('alpha2', sa.String(length=2), nullable=True),
    sa.Column('title', sa.String(length=140), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('continent', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_continent_alpha2'), ['alpha2'], unique=True)

    op.create_table('magic_number',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=140), nullable=True),
    sa.Column('count', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('magic_number', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_magic_number_title'), ['title'], unique=True)

    op.create_table('keyword',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=140), nullable=True),
    sa.Column('count', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('keyword', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_keyword_count'), ['count'], unique=False)
        batch_op.create_index(batch_op.f('ix_keyword_title'), ['title'], unique=True)

    op.create_table('group',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=16), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=256), nullable=True),
    sa.Column('name', sa.String(length=256), nullable=True),
    sa.Column('language', sa.String(length=2), nullable=True),
    sa.Column('group_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['group_id'], ['group.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_email'), ['email'], unique=True)

    op.create_table('country',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('alpha2', sa.String(length=2), nullable=True),
    sa.Column('title', sa.String(length=140), nullable=True),
    sa.Column('continent_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['continent_id'], ['continent.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('country', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_country_alpha2'), ['alpha2'], unique=True)

    op.create_table('continent_translation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('language', sa.String(length=2), nullable=True),
    sa.Column('continent_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=140), nullable=True),
    sa.ForeignKeyConstraint(['continent_id'], ['continent.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('continent_translation', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_continent_translation_language'), ['language'], unique=False)

    op.create_table('country_translation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('language', sa.String(length=2), nullable=True),
    sa.Column('country_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=140), nullable=True),
    sa.ForeignKeyConstraint(['country_id'], ['country.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('country_translation', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_country_translation_language'), ['language'], unique=False)

    op.create_table('conference',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=140), nullable=True),
    sa.Column('place', sa.String(length=256), nullable=True),
    sa.Column('starts', sa.Date(), nullable=True),
    sa.Column('ends', sa.Date(), nullable=True),
    sa.Column('deadline', sa.Date(), nullable=True),
    sa.Column('poster', sa.String(length=256), nullable=True),
    sa.Column('url', sa.String(length=256), nullable=True),
    sa.Column('email', sa.String(length=256), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('continent_id', sa.Integer(), nullable=True),
    sa.Column('country_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['continent_id'], ['continent.id'], ),
    sa.ForeignKeyConstraint(['country_id'], ['country.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('conference', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_conference_deadline'), ['deadline'], unique=False)
        batch_op.create_index(batch_op.f('ix_conference_ends'), ['ends'], unique=False)
        batch_op.create_index(batch_op.f('ix_conference_place'), ['place'], unique=False)
        batch_op.create_index(batch_op.f('ix_conference_starts'), ['starts'], unique=False)
        batch_op.create_index(batch_op.f('ix_conference_title'), ['title'], unique=False)

    op.create_table('conferences_keywords',
    sa.Column('conference_id', sa.Integer(), nullable=True),
    sa.Column('keyword_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['conference_id'], ['conference.id'], ),
    sa.ForeignKeyConstraint(['keyword_id'], ['keyword.id'], )
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('conferences_keywords')
    with op.batch_alter_table('conference', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_conference_title'))
        batch_op.drop_index(batch_op.f('ix_conference_starts'))
        batch_op.drop_index(batch_op.f('ix_conference_place'))
        batch_op.drop_index(batch_op.f('ix_conference_ends'))
        batch_op.drop_index(batch_op.f('ix_conference_deadline'))

    op.drop_table('conference')
    with op.batch_alter_table('country_translation', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_country_translation_language'))

    op.drop_table('country_translation')
    with op.batch_alter_table('continent_translation', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_continent_translation_language'))

    op.drop_table('continent_translation')
    with op.batch_alter_table('country', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_country_alpha2'))

    op.drop_table('country')
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_email'))

    op.drop_table('user')
    op.drop_table('group')
    with op.batch_alter_table('keyword', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_keyword_title'))
        batch_op.drop_index(batch_op.f('ix_keyword_count'))

    op.drop_table('keyword')
    with op.batch_alter_table('magic_number', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_magic_number_title'))

    op.drop_table('magic_number')
    with op.batch_alter_table('continent', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_continent_alpha2'))

    op.drop_table('continent')
    ### end Alembic commands ###
