"""Add table for different years query

Revision ID: 5739c763e14b
Revises: 4250dfa822a4
Create Date: 2014-12-14 11:53:32.723728

"""

# revision identifiers, used by Alembic.
revision = '5739c763e14b'
down_revision = '4250dfa822a4'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('year',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('year', sa.SmallInteger(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_year_year'), 'year', ['year'], unique=True)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_year_year'), table_name='year')
    op.drop_table('year')
    ### end Alembic commands ###
