"""Add date and provider to User model

Revision ID: 8acb1453abb
Revises: 5739c763e14b
Create Date: 2015-02-27 13:12:01.085178

"""

# revision identifiers, used by Alembic.
revision = '8acb1453abb'
down_revision = '5739c763e14b'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('user', sa.Column('created_with', sa.String(length=16), nullable=True))
    op.add_column('user', sa.Column('last_seen', sa.DateTime(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'last_seen')
    op.drop_column('user', 'created_with')
    op.drop_column('user', 'created_at')
    ### end Alembic commands ###
