"""Add remember_me

Revision ID: a6c72ec6a
Revises: 4857a4d8d76d
Create Date: 2015-03-17 20:57:18.447538

"""

# revision identifiers, used by Alembic.
revision = 'a6c72ec6a'
down_revision = '16ef0d8ffae1'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('remember_me_token', sa.String(length=128), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'remember_me_token')
    ### end Alembic commands ###
