# coding: utf-8

from functools import wraps
from htmlmin.minify import html_minify


def render_minified(html_render):
    """Minifies the HTML (string) generated by Flask's render_template()"""
    @wraps(html_render)
    def minify_it():
        return html_minify(html_render())
    return minify_it